<?php
/**
 * @var Joe\HelloModule\ViewModel\Post\PostShowViewModel $viewModel
 * @var Magento\Framework\Escaper $escaper
 */

$viewModel = $viewModel->getViewModel(); ?>
<h1><?= $escaper->escapeHtml($viewModel->getTitle()); ?></h1>

<style>
table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
tr:nth-child(even) { background-color: #dddddd; }
.post-id{width:2%} .post-name{width:30%}
</style>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php
        foreach ($viewModel->getPostCollection() as $key=>$post){
            echo '<tr>
                    <td>'.$escaper->escapeHtml($post->getPostId()).'</td>
                    <td>'.$escaper->escapeHtml($post->getPostName()).'</td>
                    <td>'.$escaper->escapeHtml($post->getPostContent()).'</td>
                  </tr>';
        }
    ?>
</table>
