<?php
/**
 * @var Joe\HelloModule\ViewModel\Post\PostEditListViewModel $viewModel
 * @var Magento\Framework\Escaper $escaper
 *
 */
$viewModel = $viewModel->getViewModel(); ?>
<h1><?= $escaper->escapeHtml($viewModel->getTitle()) ?></h1>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<style>
    table {  font-family: arial, sans-serif;  border-collapse: collapse;  width: 100%;  margin-top: 30px;}
    td, th {  border: 1px solid #dddddd;  text-align: left;  padding: 8px;  }
    tr:nth-child(even) { background-color: #ddffdd; }
    .post-id{width:2%} .post-name{width:30%} }
</style>
<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($viewModel->getPostCollection() as $key=>$post): ?>
        <tr>
            <td><?= $escaper->escapeHtml($post->getPostId()) ?></td>
            <td><?= $escaper->escapeHtml($post->getPostName()) ?></td>
            <td><?= $escaper->escapeHtml($post->getPostContent()) ?></td>
            <td>
                <a class="btn btn-warning" href="<?= $escaper->escapeUrl($viewModel->getEditFormAction((int) $post->getPostId())) ?>"><?= $escaper->escapeHtml( __('Edit')) ?></a>
                <a class="btn btn-danger" href="<?= $escaper->escapeUrl($viewModel->getDelPostAction((int) $post->getPostId())) ?>"><?= $escaper->escapeHtml( __('Delete')) ?></a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
