<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<div class="container p-5 my-5 ">
    <h1>My-CRUD Magento 2 Page</h1>
<div class="container mt-3 text-center">
    <h2>choose your button...</h2>
    <div class="row">
        <div class="col">
            <div class="card text-white">
                <div class="card-body">
                    <a href="https://212.71.250.112/hello/post/postnew" class="btn btn-primary">NEW</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card text-white">
                <div class="card-body">
                    <a href="https://212.71.250.112/hello/post/posteditlist" class="btn btn-info">UPD</a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col my-2">
            <div class="card text-white">
                <div class="card-body">
                    <a href="https://212.71.250.112/hello/post/postshow" class="btn btn-secondary">SHOW</a>
                </div>
            </div>
        </div>
        <div class="col my-2">
            <div class="card text-white">
                <div class="card-body">
                    <a href="https://212.71.250.112/hello/post/posteditlist" class="btn btn-danger">DEL</a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
